### ISSUE TITLE
Support for C client.

### ISSUE THREAD

**Issue by nijx** [hypertable/hypertable#56]
Hi, is there any support for C, as far I have been working on hypertable through the thrift client which is depend on GLIB as bridge between Thirft and C. any C API with hypertable ?

**Comment by nuggetwheat** [comment]
No, there is no native C API.  The native API is C++ only.  Does the Thrift
approach add too much overhead?

On Thu, May 28, 2015 at 2:28 PM, nijx <notifications@github.com> wrote:

> Hi, is there any support for C, as far I have been working on hypertable
> through the thrift client which is depend on GLIB as bridge between Thirft
> and C. any C API with hypertable ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hypertable/hypertable/issues/56>.
>



-- 
Doug Judd
CEO, Hypertable Inc.

**Comment by nijx** [comment]
Yes, actually median queries are 35~45% of slower using Thrift due the glib library, is there any way to get around this by using extern for C++ client ?
