### ISSUE TITLE
Download-Links on homepage are broken

### ISSUE THREAD

**Issue by ststeiger** [hypertable/hypertable#88]
The download-links are broken 
http://www.hypertable.com/download/09811
(linux x64 deb)
TucowsDomain expired.

**Comment by kashirin-alex** [comment]
I can confirm it does work on my side.

Do you mean this URL?
http://cdn.hypertable.com/packages/0.9.8.11/hypertable-0.9.8.11-linux-x86_64.deb

**Comment by ststeiger** [comment]
Never mind, was actually an issue with captive portal authentication.
/closed
