### ISSUE TITLE
RangeServer Key Size Issue

### ISSUE THREAD

**Issue by FinizX** [hypertable/hypertable#90]
Hi, my Rangeserver getting down frequently. In Range server log file I found the following line. 

htRangeServer: /rnd/devel/hypertable/hypertable/src/cc/Hypertable/Lib/Key.cc:175: bool Hypertable::Key::load(const Hypertable::SerializedKey&): Assertion `strlen(row) == row_len' failed.

But when using gdb to debug it shows strlen(row) and row_len are equal. I can't understand the exact issue. Can you help me?

**Comment by kashirin-alex** [comment]
The problem is in the input of the Key pointer and the corresponding data (gdb won't be able to find the direct cause)
causes can be a bad log fragment, cell-store or transactions related 

you need to try and see if you have any corrupted files 
https://hypertable.com/documentation/tools/ht_salvage
(https://hypertable.com/documentation/administrator_guide/diagnostic_and_recovery)
or 
before trying to recover, you can check if the error occur from a select all (KEY_ONLY will do) on the most probable table and check what were the prior taken action in the log  ( a run in a debug log-level can describe more)

**Comment by FinizX** [comment]
Hi @kashirin-alex,
Thank you for your help. I executed the following command to check corrupted files.
 
sh /opt/hypertable/current/bin/ht htck check --metadata-file metadata.tsv

I got the following output.


METADATA entries: 74
RSML range entities: 74
RSML dangling entities: 0
METADATA overlaps:  0
METADATA gaps:  0
METADATA incomplete:  0
RSML dangling fix-ups: 0
METADATA shrunk ranges:  0
Unassigned locations: 0
Unassigned start row: 0
Unassigned entities: 0
Load acknowledge fix-ups: 0

It seems files are good. Then I retrieved all tables keys using the select command with KEYS_ONLY option. All tables passed this test. Did I miss anything?

**Comment by kashirin-alex** [comment]
You didn't and in-case there was an error with select and there is a log of bad-file read the ht_salvage can save the situation

as it is not related to corrupted files, the remain probability is trx-related which is more complex to identify as a cause. The only thing for now possible is to keep track of log in debug mode. As variation are wide-spread from input by client, fs-broker & underlying fs and might be comm-layer.

If you want you can try https://github.com/kashirin-alex/hypertable/releases/tag/v0.9.8.16 . I haven't in-counted with such error while had in past.

as well, but of the topic, https://github.com/kashirin-alex/swc-db -- keep me posted if you get a chance to try (It is still at major progress)

**Comment by kashirin-alex** [comment]
You did and in-case there was an error with select and there is a log of bad-file read the ht_salvage can save the situation

as it is not related to corrupted files, the remain probability is trx-related which is more complex to identify as a cause. The only thing for now possible is to keep track of log in debug mode. As variation are wide-spread from input by client, fs-broker & underlying fs and might be comm-layer.

If you want you can try https://github.com/kashirin-alex/hypertable/releases/tag/v0.9.8.16 . I haven't in-counted with such error while had in past.

as well, but of the topic, https://github.com/kashirin-alex/swc-db -- keep me posted if you get a chance to try (It is still at major progress)

**Comment by FinizX** [comment]
I will try ht_salvage and check again. If I face the same issue again then I will try your build. 

SWC-DB is very interesting. I just read the abstract. Can I get release binaries to use it?

**Comment by kashirin-alex** [comment]
You can expect a bin release soon, It be a dual built for Debug and a Perf. sensitive. Some specific commits must be done before. (Thanks for following)

**Comment by FinizX** [comment]
Ok. I will wait for the release.

**Comment by kashirin-alex** [comment]
@FinizX have a go. (hope Ubuntu - 20.04 LTS is reachable)  
https://github.com/kashirin-alex/swc-db/releases

**Comment by kashirin-alex** [comment]
@FinizX  It be great to know if have had a test-drive. Since there is another release.
There is more in the documentations section - https://github.com/kashirin-alex/swc-db#documentations
